title: "TeamContact 24/7"
theme: jekyll-theme-cayman

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "se-edu/addressbook-level3"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
